### ISSUE TITLE
Rename directories to reflect Miami

### ISSUE THREAD

**Issue by wordyallen** [Code-for-Miami/mia-councilmatic#12]
Do this without breaking the module references. The trick is that it's relatively straight forward on localhost, but when we push to a staging server something still thinks it needs to look for chicago and then it crashes.

**Comment by ErnieAtLYD** [comment]
I'm taking a stab at this.

**Comment by ErnieAtLYD** [comment]
I fucked this up hardcode when I tried getting this running on production; so much so the server went down :( - so I rolled this back and reopened the issue.

**Comment by adamold** [comment]
Is there other stuff running on this server?

**Comment by ErnieAtLYD** [comment]
I have no idea what is happening, especially because it works great on my localhost (hard drive) and when I upload everything it throws up on itself. It may have to do with caching, so I want to see if there are some lower hanging fruit and come back to this later.
