### ISSUE TITLE
Replace "Council" with "Commission"

### ISSUE THREAD

**Issue by adamold** [Code-for-Miami/mia-councilmatic#17]

**Comment by lmgobaira** [comment]
@adamold I'd love to help with this one but need some clarification. Are you looking to replace Council in all hardcoded strings or rename any reference to council throughout the code page?

**Comment by adamold** [comment]
I only meant for the hardcoded strings.

**Comment by lmgobaira** [comment]
great. ill create a task branch and send over a MR once completed.

**Comment by ErnieAtLYD** [comment]
Any updates? I'll take a stab at this if you're no longer working on this, @lmgobaira.

**Comment by adamold** [comment]
I have been out of country. Feel free to take stab.

**Comment by lmgobaira** [comment]
adamold .. sorry about the delay lost my 2FA generator and was locked out of GitHub for a bit. 

@ErnieAtLYD ... I've made a pull request for a bulk string swap. This only affects hard coded strings in  templates and not any logic or hrefs. I have left references to "Councilmatic" in the footer to retain attribution to the creators. 

https://github.com/Code-for-Miami/mia-councilmatic/pull/26/

**Comment by adamold** [comment]
This is done for about page and index page (need to be deployed).
