### ISSUE TITLE
What is the appropriate Miami-Dade version of the about page?

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/mia-councilmatic#20]
This is what you currently see on the About Page of Chicago Councilmatic:

**What is Chicago City Council, and how does it work?**

"Chicago City Council is the legislative body of the City of Chicago. It consists of 50 elected aldermen, each representing one of Chicago's wards. City Council meets monthly and is presided over by Rahm Emanuel, the Mayor of Chicago. The secretary is Susana Mendoza, City Clerk of Chicago.

For more on how City Council works, see the City Clerk's website.

Generally, Chicago City Council deals with the following topics:
- city-wide policies - usually proposed by the mayor
- local ward matters - spearheaded by Aldermen
- matters involving individuals - miscellaneous claims & honorifics"

What would be the Miami-Dade version of this copy? @adamold, do you have ideas?

**Comment by adamold** [comment]
So, I've been thinking about categories like City-wide policies, Local Ward Matters, etc. that would make sense with regard to Miami-Dade Commission.

All their agenda items are categorized as one of these items, and I've split them into sub groups that we could list here. does this look like the proper grouping?

> CEREMONIAL
> Birthday Scroll
> Certificate of Appreciation
> Commendation
> Congratulatory Certificate
> Distinguished Visitor
> Oath of Office
> Plaque
> Proclamation
> Resolution of Sympathy
> Service Awards
> Swearing-In
> 
> AGENDA
> Additions
> Deferrals
> Supplement
> Withdrawals
> 
> ADMINISTRATIVE
> Administrative Order
> Annual Evaluation
> Change Order
> Conflict Waiver
> Nomination
> 
> BUDGET
> Omnibus Reserve
> 
> PROCUREMENT
> Bid Advertisement
> Bid Awards
> Bid Contract
> Bid Protest
> Bid Rejection
> Professional Service Agreement
> Request for Proposals
> Request for Qualifications
> Request to Advertise
> 
> PRESENTATIONS
> Citizen's Presentation
> Presentation
> Special Presentation
> Report
> 
> LEGISLATIVE
> Discussion Item
> Mayoral Veto
> Ordinance
> Public Hearing
> Resolution
> Special Item
> 
> WORKSHOPS
> Joint Meeting/Workshop
> Workshop Item
> 
> ZONING
> Zoning
> Zoning Resolution
> 
> MISC
> Miscellaneous
> Time Sensitive Items

**Comment by adamold** [comment]
Still a lot more than chicago's 3 sections.

**Comment by ErnieAtLYD** [comment]
Awesome! For categories to work within Miami's councilmatic, we'll have to make edits to the scraper. I'll go ahead and duplicate this on the Miami fork of the following repo and close this: https://github.com/Code-for-Miami/scrapers-us-municipal/issues/1
