### ISSUE TITLE
Remove refs to Legistar

### ISSUE THREAD

**Issue by adamold** [Code-for-Miami/mia-councilmatic#33]
Miami-Adde doesn't use Legistar for their code. City of Miami does. 

Seems like they self-host their legislative search, so we should make text changes to reference that. http://www.miamidade.gov/commission/search-legislation.asp

**Comment by ErnieAtLYD** [comment]
Hey @adamold - technically Miami Dade county DOES use Legistar, it's just hosted on their own servers by their IT staff. They have a "Legistar Number" search field here for example: http://www.miamidade.gov/govaction/Board_Directives.asp?function=reports&type=boarddirectives2&status=clear

**Comment by adamold** [comment]
Oh my bad.

**Comment by ErnieAtLYD** [comment]
It's okay - I had to double check with Sarasti just to be 100% sure. I'll close this issue.
