### ISSUE TITLE
Correct Committee Names/descriptions

### ISSUE THREAD

**Issue by adamold** [Code-for-Miami/mia-councilmatic#39]
in /councilmatic/settings_jurisdiction.py

**Comment by adamold** [comment]
info here: http://www.miamidade.gov/commission/library/committee-structure-member-assignments.pdf

**Comment by adamold** [comment]
Need to decide whether we want to (or can) include Boards as well as committees.

**Comment by ErnieAtLYD** [comment]
Looks good, Adam! Gonna merge this in and close.
