### ISSUE TITLE
Get @chemguy88 to teach us how the scraper stuffs data into postgres

### ISSUE THREAD

**Issue by wordyallen** [Code-for-Miami/mia-councilmatic#4]
Familiarity  with scrapers in python.
https://realpython.com/blog/python/web-scraping-with-scrapy-and-mongodb/

**Comment by ErnieAtLYD** [comment]
Define "familiarity with scrapers with python." Is the task to become familiar with scrapers to do something in particular?

**Comment by wordyallen** [comment]
umm... I currently have no clue how the scraper stuffs the data into postgres. hopefully @ChemGuy88  can shed some light.  His goals are to learn more about data science.  We chose this as a starting point.

**Comment by wordyallen** [comment]
@ChemGuy88 @ErnieAtLYD 

This seems like a MUCH better starting point: http://opencivicdata.readthedocs.org/en/latest/scrape/basics.html
