### ISSUE TITLE
Change "ward" info to "municipal" info.

### ISSUE THREAD

**Issue by adamold** [Code-for-Miami/mia-councilmatic#46]
Wards in Chicago are closest to municipalities in Miami-Dade. All references to local Ward matters should probably be local municipal matters, including on the About page.

**Comment by ErnieAtLYD** [comment]
- [X] Changed "Ward matters" tag to "Municipal matters" one

**Comment by ErnieAtLYD** [comment]
Fixed: http://162.243.115.7/about/
