### ISSUE TITLE
Legislative Topics is unpopulated

### ISSUE THREAD

**Issue by adamold** [Code-for-Miami/mia-councilmatic#51]
There are 0 of every kind of legislative topic in the menu on the about page (at the bottom)

**Comment by ErnieAtLYD** [comment]
So, did some digging into this one. Check out this file:
https://github.com/Code-for-Miami/mia-councilmatic/blob/master/chicago/helpers.py

Don't let the code scare you. What it's basically saying is "if the title starts a certain way, give them particular tags." Tags and topics are interchanging in Miami-Dade Councilmatic.

So million dollar question is, how do we split about these topics? Got a general idea where to start with this?

**Comment by adamold** [comment]
Definitely want to go with "File Name" rather than Title for this stuff. see the difference here, for example: http://www.miamidade.gov/govaction/matter.asp?matter=160904&file=false&yearFolder=Y2016

**Comment by adamold** [comment]
I wonder if we can do one of those word frequency counters to identify unique-to-category words and build the list from that?

**Comment by adamold** [comment]
Actually, forget all that. the "Indexes" field looks like it has the topics already parsed out.

**Comment by ErnieAtLYD** [comment]
Okay, so the good news is the Index is relatively easy. I'm going to submit a change to do that. 

The bad news: there are a lot, and I mean a LOT of indexes. I'm not sure which one of these are Routine or Non-Routine - even if "Routine" applies to Miami-Dade. (See city of Chicago's Councilmatic for reference: http://chicago.councilmatic.org)

What I'll do first is making everything Non-Routine. Then I'll probably have to work with you (or delegate) how to break up these into groupings so stuff is easier to find. Here's just a list of stuff I've found from the first page:

```
    # RESOLUTION RATIFYING, ALLOCATION OF FUNDS, BOND PROGRAM, ANIMALS, SOCIAL MEDIA
    # AIRPORT, MULTI-PURPOSE FACILITY, SEAPORT, POLICE, NAMING, COURTS, LIBRARY, 
    # BUILDING BETTER COMMUNITIES GENERAL OBLIGATION BOND, SURPLUS
    # CLASS I PERMIT APPLICATION, FISCAL IMPACT, PARKS, REPORT, WEBSITE, FOREIGN LANGUAGE
```
